recipe_1:
  arch: "amd64:amd64"
  machine_arch: "amd64"
  machine_combo: "amd64"

  # optional parameters
  freebsd_version: "13.2"
  img_flavor: "bootonly.iso"
  img_url: "FreeBSD-13.0-RELEASE-amd64-bootonly.iso"
  # expression for combination for testing
  # a compact possible expression later on for blacklisting define as filesystem-partition-encryption
  # a function should evaluate common combination expressions and calculate all possibilities 
  # this is acting like filter
  # regex_combination = {"ufs-gpt-geli","*-*-*","*-*-geli"},
  regex_combination: {"*-*-none"}
recipe_2:
  arch: "arm64:aarch64"
  regex_combination: {"*-gpt-none"}
